POST http://localhost:3000/api/auth/register
Content-Type: application/json


{
    "username":"suhag",
    "email":"suhag@gmail.com",
    "password":"1234"
}

### LOGIN

POST http://localhost:3000/api/auth/login
Content-Type: application/json


{
    "username":"vikasrathod",
    "password":"1234"
}


### UPDATE USER

PUT http://localhost:3000/api/users/6225acbbbdb2808d6aac1656
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NDY2MzY4ODksImV4cCI6MTY0NjYzNjk0OX0.KMpGabECrcO28ifmP4osvlkdLPEwfnuyiHDDrSdylGo
Content-Type: application/json


{
    "isAdmin":true
}



### DELETE USER

DELETE http://localhost:3000/api/users/6225acf5bdb2808d6aac165c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2Y1YmRiMjgwOGQ2YWFjMTY1YyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NDY2MzY0MzksImV4cCI6MTY0NjYzNjQ5OX0.jtNPEZ4ebz7l5y6egXogCWfbVPATyR8-PObtisPaBt8



### GET USER BY ID(ADMIN)
GET http://localhost:3000/api/users/find/6225adbcbdb2808d6aac1666
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NjYzNzI0NiwiZXhwIjoxNjQ2NzIzNjQ2fQ.dMV9X4JCdrt57Din9hXK68p4S1qX0yK9ljxosItPzBM



### GET ALL USER (ADMIN) YOU CAN QUERY FOR RECENT 5 USERS BY "?new=true"
GET http://localhost:3000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0ODIwNjI2NywiZXhwIjoxNjQ4MjkyNjY3fQ.xgFnOVvt4GgdJGhWWjjD4E9GksXzBPmgVO5VPFmrwAM


### GET USER STATS (ADMIN)

GET http://localhost:3000/api/users/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NjYzNzI0NiwiZXhwIjoxNjQ2NzIzNjQ2fQ.dMV9X4JCdrt57Din9hXK68p4S1qX0yK9ljxosItPzBM



### ADD PRODUCT(ADMIN)

POST http://localhost:3000/api/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NzU0NDk3MiwiZXhwIjoxNjQ3NjMxMzcyfQ.C8fgKkeFeCMHQWvVxXVQ2YmIPN34NPgrcTDZJ9F5NUw
Content-Type: application/json


{
        "title": "Prada Shirt",
        "desc": "This is PARADA Shirt for men, High quality 100% pure cotten is used in this product and this product is hand made by PARADA.this product and this product is hand made by PRADA.",
        "img":"https://www.prada.com/content/dam/pradanux_products/U/UCS/UCS319/1YOTF010O/UCS319_1YOT_F010O_S_182_SLF.png",
        "categories":["men","shirt","prada"],
        "size":["M","s"],
        "color":["orange"],
        "price":670
}



### UPDATE PRODUCT (ADMIN)

PUT http://localhost:3000/api/products/6226f1ae098f73f8fe0d479f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0NjYzNzI0NiwiZXhwIjoxNjQ2NzIzNjQ2fQ.dMV9X4JCdrt57Din9hXK68p4S1qX0yK9ljxosItPzBM
Content-Type: application/json



{
    "title":"Puma Shirt"
}




### GET ALL PRODUCT 

GET http://localhost:3000/api/products


### user exists in cart

GET http://localhost:3000/api/cart/exists/6225acbbbdb2808d6aac1656


### update cart

put http://localhost:3000/api/cart/6225acbbbdb2808d6aac1656
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY0OTE4Mzk2NiwiZXhwIjoxNjQ5MjcwMzY2fQ.v5m3u-XZBIOc3Ni-TGyA7q9s_B-UeI4cyFRN_ADmtfo
Content-Type: application/json

{
    "productId":123123,
    "color":"red",
    "size":"M",
    "quantity":2
}



### get income stats

GET  http://localhost:3000/api/orders/income
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MDQ2NTYyMywiZXhwIjoxNjUwNTUyMDIzfQ.BM-z3VGnwrmW2uddbVAmM5zIzjBU-2X4HlYfHYsTgqs


### GET ALL ORDERS 

GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVhY2JiYmRiMjgwOGQ2YWFjMTY1NiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY1MDQ2NjY4MywiZXhwIjoxNjUwNTUzMDgzfQ.BnICjd4O0T5W1jgH-C0m88om7kt7CtKug5o0aZj1JX0
